language: bash
install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install -y cowbuilder
  - echo -e 'MIRRORSITE=http://cdn.debian.org/debian/\nDISTRIBUTION=unstable\nBASEPATH=/home/travis/base.cow\n' > /home/travis/.pbuilderrc
  - sudo cowbuilder --create
